#!/bin/bash

TCLFILE="assemble/prbuild.tcl"
NUMPRJ=1

scriptforproject() {
	NAME=`basename $1`
	echo "# Project: $NAME" >> $TCLFILE

	# Run HLS 
    cd $1;
    vivado_hls autobuild.tcl || exit 1;
    cd ../../;
	cp $1/prj/solution1/impl/ip/hls.dcp assemble/${NAME}_synth.dcp

	# Substitute in the reconfig modules	
	echo "open_checkpoint base_static.dcp" >> $TCLFILE
	NAME=`basename $1`

	for i in $(seq 0 1 $((NUMPRJ-1))); do
		echo "read_checkpoint -cell juniper_board_i/top_${i}/U0/brg ${NAME}_synth.dcp" >> $TCLFILE
	done
            
	echo "opt_design" >> $TCLFILE
	echo "place_design" >> $TCLFILE
	echo "route_design" >> $TCLFILE
	echo "write_checkpoint ${NAME}_fulldesign_routed.dcp" >> $TCLFILE
	echo "write_bitstream -file bitstream/${NAME}.bit" >> $TCLFILE
	echo "close_project" >> $TCLFILE	
	echo "" >> $TCLFILE
}

preparescript () {
	if [ -e $TCLFILE ]; then
		rm $TCLFILE
	fi

	if [ "$1" = "" ]; then
		for d in ./reconfig/*; do
		    if [ -d $d ]; then
		    	scriptforproject $d
		    fi
		done
	else
		if [ -d ./reconfig/$1 ]; then
			scriptforproject ./reconfig/$1
		else
			echo "Directory ./reconfig/$1 does not exist."
			exit 1
		fi
	fi
}


case "$1" in 
	'all' )
		preparescript ""
		cd assemble
		vivado -mode batch -source `basename $TCLFILE`
		cd ../
	;;
	
	'single' )
		if [ "$2" = "" ]; then
			echo "Usage: $0 single <projectname>"
		else
			preparescript $2
			cd assemble
			vivado -mode batch -source `basename $TCLFILE`
			cd ../
		fi
	;;
	
	'' ) 
		echo "Usage: $0 [all | single ]"
	;;
esac
