
####################################################################################
# Generated by Vivado 2014.3 built on 'Fri Oct  3 16:31:15 MDT 2014' by 'xbuild'
# Command Used: write_xdc /home/jamie/lol.xdc
####################################################################################


# User Generated physical constraints 

create_pblock pblock_top_0
add_cells_to_pblock [get_pblocks pblock_top_0] [get_cells -quiet [list juniper_board_i/top_0/U0/brg]]

resize_pblock [get_pblocks pblock_top_0] -add {SLICE_X0Y300:SLICE_X109Y349}
resize_pblock [get_pblocks pblock_top_0] -add {DSP48_X0Y120:DSP48_X8Y139}
resize_pblock [get_pblocks pblock_top_0] -add {RAMB18_X0Y120:RAMB18_X6Y139}
resize_pblock [get_pblocks pblock_top_0] -add {RAMB36_X0Y60:RAMB36_X6Y69}

set_property RESET_AFTER_RECONFIG true [get_pblocks pblock_top_0]
set_property SNAPPING_MODE ON [get_pblocks pblock_top_0]
#create_pblock pblock_top_1
#add_cells_to_pblock [get_pblocks pblock_top_1] [get_cells -quiet [list juniper_board_i/top_1/U0/brg]]

#resize_pblock [get_pblocks pblock_top_1] -add {SLICE_X0Y100:SLICE_X109Y149}
#resize_pblock [get_pblocks pblock_top_1] -add {DSP48_X0Y40:DSP48_X8Y59}
#resize_pblock [get_pblocks pblock_top_1] -add {PCIE_X0Y0:PCIE_X0Y0}
#resize_pblock [get_pblocks pblock_top_1] -add {RAMB18_X0Y59:RAMB18_X6Y40}
#resize_pblock [get_pblocks pblock_top_1] -add {RAMB36_X0Y29:RAMB36_X6Y20}


#set_property RESET_AFTER_RECONFIG true [get_pblocks pblock_top_1]
#set_property SNAPPING_MODE ON [get_pblocks pblock_top_1]
#create_pblock pblock_top_2
#add_cells_to_pblock [get_pblocks pblock_top_2] [get_cells -quiet [list juniper_board_i/top_2/U0/brg]]

#resize_pblock [get_pblocks pblock_top_2] -add {SLICE_X0Y200:SLICE_X109Y249}
#resize_pblock [get_pblocks pblock_top_2] -add {DSP48_X0Y80:DSP48_X8Y99}
#resize_pblock [get_pblocks pblock_top_2] -add {RAMB18_X0Y80:RAMB18_X6Y99}
#resize_pblock [get_pblocks pblock_top_2] -add {RAMB36_X0Y40:RAMB36_X6Y49}

#set_property RESET_AFTER_RECONFIG true [get_pblocks pblock_top_2]
#set_property SNAPPING_MODE ON [get_pblocks pblock_top_2]
#create_pblock pblock_top_3
#add_cells_to_pblock [get_pblocks pblock_top_3] [get_cells -quiet [list juniper_board_i/top_3/U0/brg]]

#resize_pblock [get_pblocks pblock_top_3] -add {SLICE_X0Y150:SLICE_X109Y199}
#resize_pblock [get_pblocks pblock_top_3] -add {DSP48_X0Y60:DSP48_X8Y79}
#resize_pblock [get_pblocks pblock_top_3] -add {RAMB18_X0Y60:RAMB18_X6Y79}
#resize_pblock [get_pblocks pblock_top_3] -add {RAMB36_X0Y30:RAMB36_X6Y39}

#set_property RESET_AFTER_RECONFIG true [get_pblocks pblock_top_3]
#set_property SNAPPING_MODE ON [get_pblocks pblock_top_3]

