#!/bin/bash

TCLFILE="assemble/prbuild.tcl"
NUMPRJ=1

for d in ./reconfig/*; do
    if [ -d $d ]; then
        NAME=`basename $d`
        cd $d;
        vivado_hls autobuild.tcl || exit 1;
        cd ../../;
    fi

    cp $d/prj/solution1/impl/ip/hls.dcp assemble/${NAME}_synth.dcp
done


# Now substitute in the reconfig modules
for d in ./reconfig/*; do
        echo "open_checkpoint base_static.dcp" >> $TCLFILE
	if [ -d $d ]; then
		NAME=`basename $d`

		for i in $(seq 0 1 $((NUMPRJ-1))); do
    		    echo "read_checkpoint -cell juniper_board_i/top_${i}/U0/brg ${NAME}_synth.dcp" >> $TCLFILE
    		done
                
    	        echo "opt_design" >> $TCLFILE
    	        echo "place_design" >> $TCLFILE
    	        echo "route_design" >> $TCLFILE
    	        echo "write_checkpoint ${NAME}_fulldesign_routed.dcp" >> $TCLFILE
	fi

        echo "close_project" >> $TCLFILE
done

for d in ./reconfig/*; do
	if [ -d $d ]; then
		NAME=`basename $d`
		cat >> $TCLFILE <<EOF
open_checkpoint ${NAME}_fulldesign_routed.dcp
write_bitstream -file bitstream/${NAME}.bit
close_project
EOF
	fi
done

# Create the blanking bitstream
#echo "open_checkpoint base_static.dcp" >> $TCLFILE
#for i in {0..9}; do
#    if [ -d "./base/$i" ]; then
#    	echo "update_design -cell juniper_board_i/top_${i}/U0/brg -buffer_ports" >> $TCLFILE
#    fi
#done

#cat >> $TCLFILE <<EOF
#place_design
#route_design
#write_checkpoint base_static_buffer.dcp
#write_bitstream -bin_file -file bitstream/base_static_buffer.bit
#close_project
#EOF

cd assemble
vivado -mode batch -source `basename $TCLFILE`
cd ../
