#!/bin/bash

TCLFILE="assemble/prbuild.tcl"
NUMPRJ=1

if [[ $# -ne 1 ]]; then
    echo "Not enough arguments";
    echo "Usage: $0 <reconfig project>";
    exit 1;
fi

if [ -d ./reconfig/$1 ]; then
    # Build the HLS...
    cd ./reconfig/$1;
    vivado_hls autobuild.tcl || exit 1;
    cd ../../;

    cp ./reconfig/$1/prj/solution1/impl/ip/hls.dcp assemble/${1}_synth.dcp

    echo "open_checkpoint base_static.dcp" > $TCLFILE
    for i in $(seq 0 1 $((NUMPRJ-1))); do
    	echo "read_checkpoint -cell juniper_board_i/top_${i}/U0/brg ${1}_synth.dcp" >> $TCLFILE
    done

    echo "opt_design" >> $TCLFILE
    echo "place_design" >> $TCLFILE
    echo "route_design" >> $TCLFILE
    echo "write_checkpoint ${1}_fulldesign_routed.dcp" >> $TCLFILE
    echo "write_bitstream -file bitstream/${1}.bit" >> $TCLFILE
    echo "close_project" >> $TCLFILE
else
    echo "Reconfig project $1 does not exist!"
    exit 1
fi

cd assemble
vivado -mode batch -source `basename $TCLFILE`
cd ../
