#!/bin/bash

TCLFILE="assemble/basebuild.tcl"
NUMPRJ=1

# Nuke the existing output directory
rm -rf assemble

mkdir assemble
mkdir assemble/bitstream

# Copy in the designs
cp vc707_hw/vc707_hw.runs/synth_1/juniper_board_wrapper.dcp ./assemble/base_synth.dcp
cp generated.xdc ./assemble/generated.xdc
cp reconfig_4partition.xdc ./assemble/reconfig_4partition.xdc
cp base/hls/solution1/impl/ip/hls.dcp ./assemble/hls.dcp


echo "open_checkpoint base_synth.dcp" > $TCLFILE

for i in $(seq 0 1 $((NUMPRJ-1))); do
    echo "read_checkpoint -cell juniper_board_i/top_${i}/U0/brg hls.dcp" >> $TCLFILE
    echo "set_property HD.RECONFIGURABLE 1 [get_cells */top_${i}/U0/brg]" >> $TCLFILE
done

cat >> $TCLFILE <<EOF
read_xdc generated.xdc
read_xdc reconfig_4partition.xdc
opt_design
place_design
route_design
write_checkpoint base_routed.dcp
EOF

# Blank the regions
for i in $(seq 0 1 $((NUMPRJ-1))); do
    echo "update_design -cell juniper_board_i/top_${i}/U0/brg -black_box" >> $TCLFILE
done

echo "lock_design -level routing" >> $TCLFILE
echo "write_checkpoint base_static.dcp" >> $TCLFILE

# Bitstream generation!
cat >> $TCLFILE <<EOF
close_project
open_checkpoint base_routed.dcp
write_bitstream -bin_file -file bitstream/base.bit
close_project
EOF

cd assemble
vivado -mode batch -source `basename $TCLFILE`
cd ../
