
####################################################################################
# Generated by Vivado 2014.3 built on 'Fri Oct  3 16:31:15 MDT 2014' by 'xbuild'
####################################################################################


# User Generated physical constraints

create_pblock pblock_top_0
add_cells_to_pblock [get_pblocks pblock_top_0] [get_cells -quiet [list juniper_board_i/top_0/U0/brg]]
resize_pblock [get_pblocks pblock_top_0] -add {SLICE_X20Y0:SLICE_X89Y49}
resize_pblock [get_pblocks pblock_top_0] -add {DSP48_X2Y0:DSP48_X3Y19}
resize_pblock [get_pblocks pblock_top_0] -add {RAMB18_X1Y0:RAMB18_X3Y19}
resize_pblock [get_pblocks pblock_top_0] -add {RAMB36_X1Y0:RAMB36_X3Y9}
set_property RESET_AFTER_RECONFIG true [get_pblocks pblock_top_0]
set_property SNAPPING_MODE ON [get_pblocks pblock_top_0]
create_pblock pblock_top_1
add_cells_to_pblock [get_pblocks pblock_top_1] [get_cells -quiet [list juniper_board_i/top_1/U0/brg]]
resize_pblock [get_pblocks pblock_top_1] -add {SLICE_X20Y50:SLICE_X89Y99}
resize_pblock [get_pblocks pblock_top_1] -add {DSP48_X2Y20:DSP48_X3Y39}
resize_pblock [get_pblocks pblock_top_1] -add {RAMB18_X1Y20:RAMB18_X3Y39}
resize_pblock [get_pblocks pblock_top_1] -add {RAMB36_X1Y10:RAMB36_X3Y19}
set_property RESET_AFTER_RECONFIG true [get_pblocks pblock_top_1]
set_property SNAPPING_MODE ON [get_pblocks pblock_top_1]
create_pblock pblock_top_2
add_cells_to_pblock [get_pblocks pblock_top_2] [get_cells -quiet [list juniper_board_i/top_2/U0/brg]]
resize_pblock [get_pblocks pblock_top_2] -add {SLICE_X20Y150:SLICE_X89Y199}
resize_pblock [get_pblocks pblock_top_2] -add {DSP48_X2Y60:DSP48_X3Y79}
resize_pblock [get_pblocks pblock_top_2] -add {RAMB18_X1Y60:RAMB18_X3Y79}
resize_pblock [get_pblocks pblock_top_2] -add {RAMB36_X1Y30:RAMB36_X3Y39}
set_property RESET_AFTER_RECONFIG true [get_pblocks pblock_top_2]
set_property SNAPPING_MODE ON [get_pblocks pblock_top_2]
create_pblock pblock_top_3
add_cells_to_pblock [get_pblocks pblock_top_3] [get_cells -quiet [list juniper_board_i/top_3/U0/brg]]
resize_pblock [get_pblocks pblock_top_3] -add {SLICE_X20Y100:SLICE_X89Y149}
resize_pblock [get_pblocks pblock_top_3] -add {DSP48_X2Y40:DSP48_X3Y59}
resize_pblock [get_pblocks pblock_top_3] -add {RAMB18_X1Y40:RAMB18_X3Y59}
resize_pblock [get_pblocks pblock_top_3] -add {RAMB36_X1Y20:RAMB36_X3Y29}
set_property RESET_AFTER_RECONFIG true [get_pblocks pblock_top_3]
set_property SNAPPING_MODE ON [get_pblocks pblock_top_3]


