
####################################################################################
# Generated by Vivado 2014.3 built on 'Fri Oct  3 16:31:15 MDT 2014' by 'xbuild'
####################################################################################


# User Generated physical constraints

create_pblock pblock_top_0
add_cells_to_pblock [get_pblocks pblock_top_0] [get_cells -quiet [list juniper_board_i/top_0/U0/brg]]
resize_pblock [get_pblocks pblock_top_0] -add {SLICE_X20Y0:SLICE_X89Y49}
resize_pblock [get_pblocks pblock_top_0] -add {DSP48_X2Y0:DSP48_X3Y19}
resize_pblock [get_pblocks pblock_top_0] -add {RAMB18_X1Y0:RAMB18_X3Y19}
resize_pblock [get_pblocks pblock_top_0] -add {RAMB36_X1Y0:RAMB36_X3Y9}
set_property RESET_AFTER_RECONFIG true [get_pblocks pblock_top_0]
set_property SNAPPING_MODE ON [get_pblocks pblock_top_0]

